# configuration for Windows
# C:\Users\User\AppData\Roaming\Alacritty
[general]
working_directory = "C:/"

[terminal]
shell = "C:/Program Files/PowerShell/7/pwsh.exe"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "Full"
title = "Alacritty"
dimensions = { columns = 120, lines = 30}

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"
